# .goreleaser.yml
builds:
  - binary: aws-ssh
    goos:
      - darwin
      - linux
    goarch:
      - amd64
nfpm:
  vendor: Springload
  homepage: https://springload.co.nz

  maintainer: DevOps team
  description: Traverses through all available AWS accounts to generate ssh config
  license: Apache 2.0
  formats:
    - deb
    - rpm

brew:
  name: aws-ssh
  github:
    owner: springload
    name: homebrew-tools
  folder: Formula
  # Allows you to set a custom download strategy.
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
  # Allows you to add a custom require_relative at the top of the formula template
  custom_require: "../custom_download_strategy"

